export const VARIANTS = ['NECKLACE', 'BRACELET', 'EARRINGS']

export const BEADS = [
  'RED_JASPER',
  'FANCY_JASPER',
  'MUSTANG_JASPER',
  'LEOPARD_JASPER',
  'AVENTURINE',
  'CARNELIAN',
  'SAGUARO_JASPER',
  'BLACK_ONYX',
  'AMETHYST',
  'ROSE_QUARTZ',
  'CHALK_TURQUOISE',
  'SWAROVSKI',
  'YELLOW_JADE'
]
